version: "3.3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'

  migration:
    build: .
    command: python manage.py migrate --noinput
    depends_on:
      - db

  superuser:
    build: .
    command: python manage.py adminuser
    depends_on:
      - migration

  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - celery_worker
      - celery_beat
      - db
      - migration

  celery_worker:
    build: .
    command: celery -A YoutubeAPIListing worker -l info
    links:
      - redis
    depends_on:
      - db

  celery_beat:
    build: .
    command: celery -A YoutubeAPIListing beat -s ./celerybeat-schedule
    links:
      - redis
    depends_on:
      - db
